### ISSUE TITLE
MiBandDataPanel not available

### ISSUE THREAD

**Issue by Ale46** [ralfJoswig/MiBandView#2]
I was trying to compile your project but I'm getting an error about the unavailability of MiBandDataPanel package.

**Comment by ralfJoswig** [comment]
I have added a new branch (origin2) with the missing MiBandDataPanel.
Alternative you can download the latest compiled version: http://www.android-hilfe.de/xiaomi-miband-forum/677765-tool-zum-auswerten-der-ergebnisse.html
